### PR TITLE
Fix Packet.Raw set by Packet.Marshal

### LINKED ISSUE #24: Marshal after rtp.Payload == rtp.Raw ?
### What happened?
```go
rtp := &rtp.Packet{}
rtp.Unmarshal(data)

// rtp.Raw == 12 + rtp.Payload

buf, _ := rtp.Marshal()
// rtp.Raw = buf

// But 
// rtp.Raw == rtp.Payload

```
Why `rtp.Marshal()` after `rtp.Raw == rtp.Payload` ? 

Is this a feature?

### PR DESCRIPTION
**Pull request by at-wat**
#### Description

Head of `Packet.Raw` was wrong after `Packet.Marshal()`.

It was correct before:
https://github.com/pion/rtp/blame/541155ecd69be223914ccf274e9c968a17efc1f8/packet.go#L241

After #14, `Raw` points `Payload`:
https://github.com/pion/rtp/blame/master/packet.go#L267

#### Reference issue
Fixes #24

### CODE REVIEW

**Comment by at-wat** [comment]
@kixelated please take a look!

**Comment by at-wat** [comment]
@adwpc @Antonito @wdouglass @Sean-Der Please take a look if you have time.

File: packet.go [hunk 1]
```diff
@@ -264,7 +264,7 @@ func (p *Packet) MarshalTo(buf []byte) (n int, err error) {
 	}
 
 	m := copy(buf[n:], p.Payload)
-	p.Raw = buf[n : n+m]
+	p.Raw = buf[:n+m]
```
Comment (wdouglass) [inline packet.go]: hmmm...surprised this problem has existed this long. good catch!
